version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Bangkok
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Asia/Bangkok
    groups:
      python-packaging:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: "/deploy"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Asia/Bangkok
    groups:
      container-bases:
        patterns:
          - "*"
    open-pull-requests-limit: 5
